<html lang="en-US"> <!--<![endif]-->
    <head>

        <!-- Meta Tags -->
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

        <title>inicio</title>   

        <meta name="description" content="Insert Your Site Description" /> 

        <!-- Mobile Specifics -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="HandheldFriendly" content="true"/>
        <meta name="MobileOptimized" content="320"/>   

        <!-- Mobile Internet Explorer ClearType Technology -->
        <!--[if IEMobile]>  <meta http-equiv="cleartype" content="on">  <![endif]-->
        <?php Tag::css('bruset/bootstrap.min') ?>    
        <?php Tag::css('bruset/main') ?> 
        <?php Tag::css('bruset/supersized') ?>
        <?php Tag::css('bruset/supersized.shutter') ?>
        <?php Tag::css('bruset/fancybox/jquery.fancybox') ?>
        <!-- Font Icons -->
        <?php Tag::css('bruset/fonts') ?>
        <!-- Shortcodes -->
        <?php Tag::css('bruset/shortcodes') ?>
        <!-- Responsive -->
        <?php Tag::css('bruset/bootstrap-responsive.min') ?>
        <?php Tag::css('bruset/responsive') ?>
        <!-- Supersized -->
        <?php Tag::css('bruset/supersized') ?>
        <?php Tag::css('bruset/supersized.shutter') ?>
         <?php echo Html::includeCss() ?>
        <!-- Google Font -->
        <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900' rel='stylesheet' type='text/css'>

        <!-- Fav Icon -->
        <link rel="shortcut icon" href="<?php echo PUBLIC_PATH?>img/default/favicon.ico" type="image/x-icon" />

        <!-- Modernizr -->
    <?php echo tag::js('bruset/modernizr');?>
    </head>
    <body>
        <?php View::partial('sbadmin/bruset') ?>
    </body>
    