<?php
$err = isset($_GET['error']) ? $_GET['error'] : null;
         Load::model('persona');
         $gestores = new persona();
       $asd = session::get('rojo');
  ?>
<div style="text-align: center;background-color: buttonhighlight"><h3>Envio de correos</h3></div>
            <?php
            if ($err == 2) {
                echo "<div class='alert alert-danger text-center'><strong>Adventencia:"
                . " </strong>No se pudo enviar el correo ".$asd."</div>";
            }
            if ($err == 1) {
                echo "<div class='alert alert-success text-center'><strong>Adventencia: "
                . "</strong>El correo fue enviado</div>";
            }
            ?>
<br>
<br>

        <div class="col-lg-10">
            <form  role="form" class="form-horizontal" action="correo" method="post">
                            <div class="form-group">
                <label for="Email" class="control-label col-xs-5">E-mail:</label>
                <div class="col-xs-5">
                    <input id="Email" name="Email" type="text" 
                           class="form-control" placeholder="Email" onkeyup="validacion('Email');" required="">
                    <span class="help-block"></span>
                </div> </div>
                     <div class="form-group">
                <label for="nombre" class="control-label col-xs-5">Contraseña:</label>
                <div class="col-xs-5">
                    <input id="nombre" name="nombre" type="password" class="form-control"
                           placeholder="Contraseña" onkeyup="validacion('nombre');" required="">
                    <span class="help-block"></span>
                </div>
        </div>
                <br>
<table class="table table-bordered">
<thead><td>Gestor predial</td><td>Correo electronico</td></thead>
   <?php foreach ($p = $gestores->cor() as $s) {?>
<tr>
    <td><?php echo  $s->a ?></td>
    <td><?php echo $s->b ?></td>
</tr>                    
          <?php } ?>

</table>
                      <div style="margin-left: 630px;">
                <button type="submit" class="btn btn-primary">Enviar correo</button></div>
         </form>
            </div>


    <?php echo Tag::js('validacion/js/validacion') ?> 